import assert from "node:assert/strict"
import { spawnSync } from "node:child_process"
import { createRequire } from "node:module"
import { tmpdir } from "node:os"
import path from "node:path"
import {
  access,
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  realpath,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises"
import { fileURLToPath, pathToFileURL } from "node:url"

const scriptFile = fileURLToPath(import.meta.url)
const skillRoot = path.resolve(path.dirname(scriptFile), "..")
const repositoryRoot = path.resolve(skillRoot, "..", "..")
const referencesRoot = path.join(skillRoot, "references")
const generatedRoot = path.join(referencesRoot, "generated")
const selectionFile = path.join(skillRoot, "package-selection.json")
const generatedFileNames = ["component-exports.md", "token-paths.md"]
const generatedNotice = "<!-- Generated by scripts/update.mjs. Do not edit by hand. -->"

const approvedPackages = {
  tokens: {
    workspace: "packages/tokens",
    name: "@exre/exui-tokens",
  },
  components: {
    workspace: "packages/components",
    name: "@exre/exui",
  },
}

function fail(message) {
  throw new Error(message)
}

function requireCondition(condition, message) {
  if (!condition) {
    fail(message)
  }
}

function normalizeLineEndings(value) {
  return value.replace(/\r\n/g, "\n")
}

function sortUnique(values) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right, "en"))
}

function isWithin(base, candidate) {
  const relative = path.relative(base, candidate)
  return relative === "" || (!relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative))
}

function requireWithin(base, candidate, label) {
  requireCondition(isWithin(base, candidate), `${label} resolves outside the allowed directory`)
}

function getExportTarget(manifest, exportName, condition) {
  const exported = manifest.exports?.[exportName]
  if (typeof exported === "string") {
    return exported
  }
  if (exported && typeof exported === "object" && typeof exported[condition] === "string") {
    return exported[condition]
  }
  fail(`${manifest.name}: export ${exportName} does not expose ${condition}`)
}

function validateExportTarget(packageDirectory, target, label) {
  const resolved = path.resolve(packageDirectory, target)
  requireWithin(packageDirectory, resolved, label)
  return target
}

async function readJson(filePath) {
  try {
    return JSON.parse(await readFile(filePath, "utf8"))
  } catch (error) {
    fail(`${path.basename(filePath)} is not readable JSON: ${error.message}`)
  }
}

async function pathExists(candidate) {
  try {
    await access(candidate)
    return true
  } catch {
    return false
  }
}

async function validatePackageSelection(root, selection) {
  requireCondition(selection && typeof selection === "object", "package selection must be an object")
  requireCondition(Array.isArray(selection.packages), "package selection must contain a packages array")
  requireCondition(selection.packages.length === 2, "package selection must contain exactly two packages")

  const roles = selection.packages.map((entry) => entry?.role)
  requireCondition(new Set(roles).size === roles.length, "package selection roles must be unique")
  requireCondition(roles.includes("tokens") && roles.includes("components"), "package selection must contain tokens and components roles")

  const canonicalRoot = await realpath(root)
  const result = {}

  for (const role of ["tokens", "components"]) {
    const entry = selection.packages.find((candidate) => candidate.role === role)
    const approved = approvedPackages[role]
    requireCondition(entry.workspace === approved.workspace, `${role}: unapproved workspace ${String(entry.workspace)}`)
    requireCondition(entry.name === approved.name, `${role}: package name must be ${approved.name}`)

    const unresolvedDirectory = path.resolve(canonicalRoot, entry.workspace)
    requireWithin(canonicalRoot, unresolvedDirectory, `${role} workspace`)
    const packageDirectory = await realpath(unresolvedDirectory).catch(() => fail(`${role}: workspace does not exist`))
    requireWithin(canonicalRoot, packageDirectory, `${role} workspace`)

    const manifestPath = path.join(packageDirectory, "package.json")
    const manifest = await readJson(manifestPath)
    requireCondition(manifest.name === entry.name, `${role}: package manifest name does not match selection`)
    requireCondition(manifest.private !== true, `${role}: private packages cannot be selected`)
    requireCondition(manifest.exports && manifest.exports["."], `${role}: package root export is missing`)

    if (role === "tokens") {
      validateExportTarget(packageDirectory, getExportTarget(manifest, ".", "import"), `${role} root export`)
      validateExportTarget(packageDirectory, getExportTarget(manifest, "./style.css", "default"), `${role} style export`)
      validateExportTarget(packageDirectory, getExportTarget(manifest, "./font.css", "default"), `${role} font export`)
    } else {
      validateExportTarget(packageDirectory, getExportTarget(manifest, ".", "types"), `${role} type export`)
    }

    result[role] = { directory: packageDirectory, manifest }
  }

  return result
}

async function loadPackageSelection(root = repositoryRoot, filePath = selectionFile) {
  return validatePackageSelection(root, await readJson(filePath))
}

function runPnpm(args, stage) {
  // Node cannot spawn a .cmd shim with shell disabled on Windows. Run the
  // Corepack pnpm entry with the current Node executable to preserve the
  // argument-array and no-shell boundary required by this updater.
  const isWindows = process.platform === "win32"
  const executable = isWindows ? process.execPath : "pnpm"
  const pnpmArguments = isWindows
    ? [path.join(path.dirname(process.execPath), "node_modules", "corepack", "dist", "pnpm.js"), ...args]
    : args
  const result = spawnSync(executable, pnpmArguments, {
    cwd: repositoryRoot,
    shell: false,
    stdio: "inherit",
  })

  if (result.error) {
    fail(`${stage}: unable to run pnpm: ${result.error.message}`)
  }
  if (result.status !== 0) {
    fail(`${stage}: pnpm exited with status ${String(result.status)}`)
  }
}

function buildPublicEntries() {
  runPnpm(["--filter", "@exre/exui-tokens", "build"], "tokens build")
  runPnpm(["--filter", "@exre/exui", "build:types"], "component types build")
}

function isPlainObject(value) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false
  }
  const prototype = Object.getPrototypeOf(value)
  return prototype === Object.prototype || prototype === null
}

function isRecipeReference(value) {
  if (!isPlainObject(value)) {
    return false
  }
  const keys = Object.keys(value).sort()
  return keys.length === 2 && keys[0] === "path" && keys[1] === "scope" && typeof value.path === "string" && typeof value.scope === "string"
}

function collectLeafPaths(rootValue, rootName, { allowRecipeReferences = false } = {}) {
  requireCondition(isPlainObject(rootValue), `${rootName} must be a plain object`)
  const paths = []
  const ancestors = new WeakSet()

  function visit(value, currentPath) {
    if (value === null || ["string", "number", "boolean"].includes(typeof value)) {
      paths.push(currentPath)
      return
    }
    requireCondition(!Array.isArray(value), `${currentPath}: arrays are not supported`)
    requireCondition(isPlainObject(value), `${currentPath}: non-plain objects are not supported`)

    const enumerableSymbols = Object.getOwnPropertySymbols(value).filter((symbol) => Object.prototype.propertyIsEnumerable.call(value, symbol))
    requireCondition(enumerableSymbols.length === 0, `${currentPath}: enumerable symbol keys are not supported`)
    if (allowRecipeReferences && isRecipeReference(value)) {
      paths.push(currentPath)
      return
    }

    requireCondition(!ancestors.has(value), `${currentPath}: cyclic object detected`)
    const keys = Object.keys(value)
    requireCondition(keys.length > 0, `${currentPath}: empty objects are not supported`)
    ancestors.add(value)
    for (const key of keys.sort((left, right) => left.localeCompare(right, "en"))) {
      visit(value[key], `${currentPath}.${key}`)
    }
    ancestors.delete(value)
  }

  visit(rootValue, rootName)
  return sortUnique(paths)
}

function collectCssProperties(css) {
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "")
  const names = []
  const declaration = /(?:^|[;{])\s*(--[A-Za-z0-9_-]+)\s*:/g
  let match
  while ((match = declaration.exec(withoutComments)) !== null) {
    names.push(match[1])
  }
  requireCondition(names.length > 0, "token stylesheet contains no CSS custom-property declarations")
  return sortUnique(names)
}

function requireStringInventory(values, prefix, label) {
  requireCondition(Array.isArray(values) && values.length > 0, `${label} inventory must be a non-empty array`)
  for (const value of values) {
    requireCondition(typeof value === "string" && value.startsWith(prefix), `${label} inventory accepts names only`)
    requireCondition(!value.includes("\n") && !value.includes("`"), `${label} inventory contains an invalid name`)
  }
}

function renderTokenInventory({ tokenPaths, recipePaths, cssProperties }) {
  requireStringInventory(tokenPaths, "exuiTokens.", "exuiTokens")
  requireStringInventory(recipePaths, "componentRecipes.", "componentRecipes")
  requireStringInventory(cssProperties, "--", "CSS custom properties")

  const section = (heading, values) => [`## ${heading}`, "", ...sortUnique(values).map((value) => `- \`${value}\``), ""]
  return [
    generatedNotice,
    "",
    "# ExUI Token Paths",
    "",
    "This inventory lists public names only. It intentionally excludes resolved Token values.",
    "",
    ...section("exuiTokens", tokenPaths),
    ...section("componentRecipes", recipePaths),
    ...section("CSS custom properties", cssProperties),
  ].join("\n")
}

async function loadTokenInventory(tokensPackage) {
  const javascriptTarget = getExportTarget(tokensPackage.manifest, ".", "import")
  const stylesheetTarget = getExportTarget(tokensPackage.manifest, "./style.css", "default")
  const javascriptEntry = path.resolve(tokensPackage.directory, javascriptTarget)
  const stylesheetEntry = path.resolve(tokensPackage.directory, stylesheetTarget)
  requireWithin(tokensPackage.directory, javascriptEntry, "tokens JavaScript export")
  requireWithin(tokensPackage.directory, stylesheetEntry, "tokens stylesheet export")

  const cacheKey = (await stat(javascriptEntry)).mtimeMs
  const publicModule = await import(`${pathToFileURL(javascriptEntry).href}?updated=${cacheKey}`)
  requireCondition(publicModule.exuiTokens, "tokens root export does not contain exuiTokens")
  requireCondition(publicModule.componentRecipes, "tokens root export does not contain componentRecipes")

  return {
    tokenPaths: collectLeafPaths(publicModule.exuiTokens, "exuiTokens"),
    recipePaths: collectLeafPaths(publicModule.componentRecipes, "componentRecipes", { allowRecipeReferences: true }),
    cssProperties: collectCssProperties(await readFile(stylesheetEntry, "utf8")),
  }
}

function normalizedReferenceKey(value) {
  return value.replace(/[^A-Za-z0-9]/g, "").toLowerCase()
}

function pascalCaseFileName(value) {
  return value.split("-").map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`).join("")
}

function classifyDeclaration(componentDirectory, declarationFile, referenceNames) {
  requireWithin(componentDirectory, declarationFile, "component declaration")
  const relative = path.relative(componentDirectory, declarationFile).split(path.sep).join("/")
  let match = /^types\/components\/ui\/(.+)\.d\.ts$/.exec(relative)
  if (match) {
    const referenceName = referenceNames.get(normalizedReferenceKey(match[1]))
    return {
      category: "Components",
      family: referenceName ?? pascalCaseFileName(match[1]),
      reference: referenceName ? `../components/${referenceName}.md` : null,
    }
  }
  if (relative === "types/components/theme-provider.d.ts") {
    return { category: "Theme provider", family: null, reference: null }
  }
  match = /^types\/hooks\/(.+)\.d\.ts$/.exec(relative)
  if (match) {
    return { category: "Hooks", family: null, reference: null }
  }
  match = /^types\/lib\/(.+)\.d\.ts$/.exec(relative)
  if (match) {
    return { category: "Utilities", family: null, reference: null }
  }
  fail(`component export declaration has no approved group: ${relative}`)
}

function symbolKind(ts, symbol) {
  const isValue = (symbol.flags & ts.SymbolFlags.Value) !== 0
  const isType = (symbol.flags & ts.SymbolFlags.Type) !== 0
  requireCondition(isValue || isType, `component export ${symbol.name} is neither a value nor a type`)
  if (isValue && isType) {
    return "value + type"
  }
  return isValue ? "value" : "type"
}

async function loadComponentInventory(componentsPackage) {
  const typesTarget = getExportTarget(componentsPackage.manifest, ".", "types")
  const declarationEntry = path.resolve(componentsPackage.directory, typesTarget)
  requireWithin(componentsPackage.directory, declarationEntry, "component type export")

  const requireFromPackage = createRequire(path.join(componentsPackage.directory, "package.json"))
  const ts = requireFromPackage("typescript")
  const program = ts.createProgram({
    rootNames: [declarationEntry],
    options: {
      jsx: ts.JsxEmit.ReactJSX,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      noEmit: true,
      skipLibCheck: true,
      target: ts.ScriptTarget.ESNext,
    },
  })

  const diagnostics = program.getSyntacticDiagnostics()
  requireCondition(diagnostics.length === 0, `component declaration entry has ${diagnostics.length} syntax diagnostic(s)`)
  const sourceFile = program.getSourceFile(declarationEntry)
  requireCondition(sourceFile, "component declaration entry was not loaded")
  const checker = program.getTypeChecker()
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile)
  requireCondition(moduleSymbol, "component declaration entry has no module symbol")

  const componentReferences = new Map()
  const componentReferenceDirectory = path.join(referencesRoot, "components")
  for (const entry of await readdir(componentReferenceDirectory, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".md")) {
      const stem = entry.name.slice(0, -3)
      componentReferences.set(normalizedReferenceKey(stem), stem)
    }
  }

  const inventory = []
  for (const exportedSymbol of checker.getExportsOfModule(moduleSymbol)) {
    const targetSymbol = (exportedSymbol.flags & ts.SymbolFlags.Alias) !== 0 ? checker.getAliasedSymbol(exportedSymbol) : exportedSymbol
    const declarations = [...(targetSymbol.getDeclarations?.() ?? []), ...(exportedSymbol.getDeclarations?.() ?? [])]
      .map((declaration) => path.resolve(declaration.getSourceFile().fileName))
      .filter((fileName) => isWithin(componentsPackage.directory, fileName))
    const repositoryDeclarations = sortUnique(declarations)
    requireCondition(repositoryDeclarations.length > 0, `component export ${exportedSymbol.name} has no repository declaration`)

    const classifications = repositoryDeclarations.map((fileName) => classifyDeclaration(componentsPackage.directory, fileName, componentReferences))
    const groupingKeys = new Set(classifications.map(({ category, family }) => `${category}\u0000${family ?? ""}`))
    requireCondition(groupingKeys.size === 1, `component export ${exportedSymbol.name} has conflicting declaration groups`)
    inventory.push({
      name: exportedSymbol.name,
      kind: symbolKind(ts, targetSymbol),
      ...classifications[0],
    })
  }

  requireCondition(inventory.length > 0, "component root export inventory is empty")
  return inventory
}

function renderComponentInventory(inventory) {
  requireCondition(Array.isArray(inventory) && inventory.length > 0, "component inventory must be non-empty")
  const categories = new Map()
  for (const entry of inventory) {
    requireCondition(typeof entry.name === "string" && !entry.name.includes("\n"), "component inventory contains an invalid export name")
    const family = entry.family ?? ""
    const familyMap = categories.get(entry.category) ?? new Map()
    const entries = familyMap.get(family) ?? []
    entries.push(entry)
    familyMap.set(family, entries)
    categories.set(entry.category, familyMap)
  }

  const categoryOrder = ["Components", "Theme provider", "Hooks", "Utilities"]
  const lines = [
    generatedNotice,
    "",
    "# ExUI Component Exports",
    "",
    "This inventory covers exports reachable from the public `@exre/exui` package root. Import every listed symbol from that root.",
    "",
  ]

  for (const category of categoryOrder) {
    const familyMap = categories.get(category)
    if (!familyMap) {
      continue
    }
    lines.push(`## ${category}`, "")
    for (const family of [...familyMap.keys()].sort((left, right) => left.localeCompare(right, "en"))) {
      const entries = familyMap.get(family).sort((left, right) => left.name.localeCompare(right.name, "en"))
      if (family) {
        const reference = entries.find((entry) => entry.reference)?.reference
        lines.push(reference ? `### [${family}](${reference})` : `### ${family}`, "")
      }
      for (const entry of entries) {
        lines.push(`- \`${entry.name}\` — ${entry.kind}`)
      }
      lines.push("")
    }
  }

  const renderedCount = lines.filter((line) => line.startsWith("- `")).length
  requireCondition(renderedCount === inventory.length, "component renderer omitted one or more exports")
  return lines.join("\n")
}

function extractRelativeLinks(markdown) {
  const links = []
  const pattern = /\[[^\]]*\]\(([^)]+)\)/g
  let match
  while ((match = pattern.exec(markdown)) !== null) {
    if (!match[1].startsWith("#") && !/^[a-z]+:/i.test(match[1])) {
      links.push(match[1])
    }
  }
  return links
}

function validateLucideExamples(markdown, label) {
  const codeFence = /```(?:tsx|jsx)\n([\s\S]*?)```/g
  let match
  while ((match = codeFence.exec(markdown)) !== null) {
    if (/<[A-Z][A-Za-z0-9]*Icon\b/.test(match[1])) {
      requireCondition(/from\s+["']lucide-react["']/.test(match[1]), `${label}: Lucide JSX example is missing its lucide-react import`)
    }
  }
}

async function validateRelativeLinks(root, filePath, markdown, virtualGenerated) {
  for (const relativeLink of extractRelativeLinks(markdown)) {
    const pathOnly = relativeLink.split("#", 1)[0]
    if (!pathOnly) {
      continue
    }
    const resolved = path.resolve(path.dirname(filePath), pathOnly)
    requireWithin(root, resolved, `${path.basename(filePath)} link ${relativeLink}`)
    const generatedName = path.basename(resolved)
    const isVirtualGenerated = path.dirname(resolved) === path.join(root, "references", "generated") && virtualGenerated.has(generatedName)
    requireCondition(isVirtualGenerated || await pathExists(resolved), `${path.basename(filePath)} link does not exist: ${relativeLink}`)
  }
}

async function validateHumanDocuments(root, virtualGenerated = new Set(generatedFileNames)) {
  const skillFilePath = path.join(root, "SKILL.md")
  const skill = normalizeLineEndings(await readFile(skillFilePath, "utf8"))
  const metadata = normalizeLineEndings(await readFile(path.join(root, "agents", "openai.yaml"), "utf8"))
  const tokenGuide = normalizeLineEndings(await readFile(path.join(root, "references", "token-usage.md"), "utf8"))
  const iconGuide = normalizeLineEndings(await readFile(path.join(root, "references", "icon-usage.md"), "utf8"))

  requireCondition(/^---\n[\s\S]*?^name: exui-usage$/m.test(skill), "SKILL.md name must be exui-usage")
  requireCondition(/^description: .*Token.*component.*icon/im.test(skill), "SKILL.md description must distinguish Token, component, and icon requests")
  requireCondition(metadata.includes("$exui-usage"), "openai.yaml default prompt must invoke $exui-usage")

  await validateRelativeLinks(root, skillFilePath, skill, virtualGenerated)
  await validateRelativeLinks(root, path.join(root, "references", "token-usage.md"), tokenGuide, virtualGenerated)
  await validateRelativeLinks(root, path.join(root, "references", "icon-usage.md"), iconGuide, virtualGenerated)
  validateLucideExamples(iconGuide, "icon-usage.md")

  const componentDirectory = path.join(root, "references", "components")
  const componentFiles = await readdir(componentDirectory, { withFileTypes: true })
  const componentContents = []
  requireCondition(componentFiles.some((entry) => entry.isFile() && entry.name.endsWith(".md")), "component references are missing")
  for (const entry of componentFiles) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) {
      continue
    }
    const componentFilePath = path.join(componentDirectory, entry.name)
    const content = normalizeLineEndings(await readFile(componentFilePath, "utf8"))
    componentContents.push(content)
    await validateRelativeLinks(root, componentFilePath, content, virtualGenerated)
    validateLucideExamples(content, entry.name)
    requireCondition(!/^Source:\s*`(?:src|dist|types)\//m.test(content), `${entry.name}: repository source declaration is not a consumer contract`)
    requireCondition(!/from\s+["']@exre\/exui(?:-tokens)?\/(?:src|dist|types)(?:\/|["'])/.test(content), `${entry.name}: private package import detected`)
  }

  const combined = [skill, metadata, tokenGuide, iconGuide, ...componentContents].join("\n")
  const replacedInvocation = ["$exui", "components"].join("-")
  const replacedDisplayName = ["Exre", "UI", "Components"].join(" ")
  requireCondition(!combined.includes(replacedInvocation) && !combined.includes(replacedDisplayName), "new skill contains the replaced skill name")
  requireCondition(!/@exre\/exui(?:-tokens)?\/(?:src|dist|types)(?:\/|["'`\s)]|$)/.test(combined), "new skill contains a private package import path")

  for (const required of [
    "@exre/exui/style.css",
    "@exre/exui-tokens/style.css",
    "@exre/exui-tokens/font.css",
    "componentRecipes",
    "surface",
    "text",
    "control",
    "border",
    "feedback",
    "editor",
    "chart",
    "sidebar",
    "density",
    "typography",
    "radii",
    "shadows",
  ]) {
    requireCondition(tokenGuide.includes(required), `token-usage.md is missing required guidance: ${required}`)
  }
  for (const required of ["lucide-react", "direct dependency", "brand logo", "product-specific", "aria-label", "aria-hidden"]) {
    requireCondition(iconGuide.toLowerCase().includes(required.toLowerCase()), `icon-usage.md is missing required guidance: ${required}`)
  }
}

function validateGeneratedOutputs(outputs, expected) {
  requireCondition(Object.keys(outputs).sort().join("\n") === generatedFileNames.join("\n"), "generated output set is incomplete")
  requireCondition(outputs["token-paths.md"] === renderTokenInventory(expected.tokens), "Token renderer is not deterministic")
  requireCondition(outputs["component-exports.md"] === renderComponentInventory(expected.components), "component renderer is not deterministic")
  for (const [name, content] of Object.entries(outputs)) {
    requireCondition(content.startsWith(generatedNotice), `${name}: generated notice is missing`)
    requireCondition(!content.includes("\r"), `${name}: generated output must use LF line endings`)
    requireCondition(content.endsWith("\n"), `${name}: generated output must end with a newline`)
  }
}

async function validateGeneratedDirectory(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const names = entries.filter((entry) => entry.isFile()).map((entry) => entry.name).sort()
  requireCondition(entries.every((entry) => entry.isFile()), `${path.basename(directory)} contains an unexpected directory`)
  requireCondition(names.join("\n") === generatedFileNames.join("\n"), `${path.basename(directory)} does not contain the complete generated file set`)
  for (const name of names) {
    const content = await readFile(path.join(directory, name), "utf8")
    requireCondition(content.startsWith(generatedNotice), `${name}: generated notice is missing`)
    requireCondition(!content.includes("\r") && content.endsWith("\n"), `${name}: generated file format is invalid`)
    const inventoryLines = content.split("\n").filter((line) => line.startsWith("- `"))
    requireCondition(inventoryLines.length > 0, `${name}: generated inventory is empty`)
    if (name === "token-paths.md") {
      for (const prefix of ["exuiTokens.", "componentRecipes.", "--"]) {
        requireCondition(inventoryLines.some((line) => line.startsWith(`- \`${prefix}`)), `${name}: ${prefix} inventory is missing`)
      }
      requireCondition(inventoryLines.every((line) => /^- `(?:exuiTokens\.|componentRecipes\.|--)[^`]+`$/.test(line)), `${name}: generated Token line is invalid`)
    } else {
      requireCondition(inventoryLines.every((line) => /^- `[^`]+` — (?:value|type|value \+ type)$/.test(line)), `${name}: generated component line is invalid`)
    }
  }
}

async function recoverInterruptedWrite(referenceDirectory = referencesRoot, operations = { rename }) {
  const target = path.join(referenceDirectory, "generated")
  const backup = path.join(referenceDirectory, ".generated-backup")
  const entries = await readdir(referenceDirectory, { withFileTypes: true })
  const temporaryEntries = entries.filter((entry) => entry.name.startsWith(".generated-tmp-"))
  requireCondition(temporaryEntries.length === 0, "unfinished generated temporary directory requires manual inspection")

  if (!await pathExists(backup)) {
    return
  }
  requireCondition(!await pathExists(target), "generated directory and backup both exist; refusing to guess which is current")
  await validateGeneratedDirectory(backup)
  await operations.rename(backup, target)
}

async function replaceGeneratedDirectory(outputs, referenceDirectory = referencesRoot, operations = { rename, rm }) {
  const target = path.join(referenceDirectory, "generated")
  const backup = path.join(referenceDirectory, ".generated-backup")
  await recoverInterruptedWrite(referenceDirectory, operations)
  const temporary = await mkdtemp(path.join(referenceDirectory, ".generated-tmp-"))
  let hadOriginal = false
  let originalMoved = false
  let replacementInstalled = false

  try {
    for (const name of generatedFileNames) {
      await writeFile(path.join(temporary, name), outputs[name], "utf8")
    }
    await validateGeneratedDirectory(temporary)

    hadOriginal = await pathExists(target)
    if (hadOriginal) {
      await operations.rename(target, backup)
      originalMoved = true
    }
    await operations.rename(temporary, target)
    replacementInstalled = true
    await validateGeneratedDirectory(target)
  } catch (error) {
    if (replacementInstalled && await pathExists(target)) {
      await operations.rm(target, { recursive: true, force: true })
    }
    if (originalMoved && await pathExists(backup)) {
      await operations.rename(backup, target)
    }
    if (await pathExists(temporary)) {
      await operations.rm(temporary, { recursive: true, force: true })
    }
    throw error
  }

  if (hadOriginal) {
    await operations.rm(backup, { recursive: true, force: true })
  }
}

async function checkGeneratedDirectory(outputs, directory = generatedRoot) {
  const changed = []
  for (const name of generatedFileNames) {
    const existing = await readFile(path.join(directory, name), "utf8").catch(() => null)
    if (existing !== outputs[name]) {
      changed.push(name)
    }
  }
  const extra = await readdir(directory, { withFileTypes: true }).catch(() => [])
  for (const entry of extra) {
    if (!generatedFileNames.includes(entry.name)) {
      changed.push(entry.name)
    }
  }
  requireCondition(changed.length === 0, `generated references are stale: ${sortUnique(changed).join(", ")}`)
}

async function expectRejection(action, expectedMessage) {
  let rejected = false
  try {
    await action()
  } catch (error) {
    rejected = true
    requireCondition(error.message.includes(expectedMessage), `expected failure containing ${expectedMessage}, received: ${error.message}`)
  }
  requireCondition(rejected, `expected rejection containing ${expectedMessage}`)
}

async function writeFixtureManifest(directory, manifest) {
  await mkdir(directory, { recursive: true })
  await writeFile(path.join(directory, "package.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8")
}

async function createHumanDocumentFixture(root) {
  await mkdir(path.join(root, "agents"), { recursive: true })
  await mkdir(path.join(root, "references", "components"), { recursive: true })
  await writeFile(path.join(root, "SKILL.md"), `---\nname: exui-usage\ndescription: Guide Token, component, and icon consumers.\n---\n\n[Tokens](references/token-usage.md)\n[Icons](references/icon-usage.md)\n[Generated](references/generated/token-paths.md)\n`, "utf8")
  await writeFile(path.join(root, "agents", "openai.yaml"), `interface:\n  default_prompt: "Use $exui-usage now."\n`, "utf8")
  await writeFile(path.join(root, "references", "token-usage.md"), `@exre/exui/style.css @exre/exui-tokens/style.css @exre/exui-tokens/font.css componentRecipes surface text control border feedback editor chart sidebar density typography radii shadows\n`, "utf8")
  await writeFile(path.join(root, "references", "icon-usage.md"), `lucide-react direct dependency brand logo product-specific aria-label aria-hidden\n`, "utf8")
  await writeFile(path.join(root, "references", "components", "Button.md"), `import { Button } from "@exre/exui"\n`, "utf8")
}

async function runSelfTest() {
  const root = await mkdtemp(path.join(tmpdir(), "exui-usage-self-test-"))
  try {
    const tokenFixture = { z: "last", a: { second: 2, first: 1 } }
    assert.deepEqual(collectLeafPaths(tokenFixture, "exuiTokens"), ["exuiTokens.a.first", "exuiTokens.a.second", "exuiTokens.z"])
    assert.deepEqual(collectLeafPaths({ button: { color: { scope: "semantic", path: "control.primary" } } }, "componentRecipes", { allowRecipeReferences: true }), ["componentRecipes.button.color"])
    assert.deepEqual(collectCssProperties("@supports (--not-a-declaration: value) { :root { --z: red; color: var(--ignored); --a: blue; } }"), ["--a", "--z"])
    const tokenRenderInput = {
      tokenPaths: ["exuiTokens.z", "exuiTokens.a"],
      recipePaths: ["componentRecipes.z", "componentRecipes.a"],
      cssProperties: ["--z", "--a"],
    }
    assert.equal(renderTokenInventory(tokenRenderInput), renderTokenInventory({
      tokenPaths: [...tokenRenderInput.tokenPaths].reverse(),
      recipePaths: [...tokenRenderInput.recipePaths].reverse(),
      cssProperties: [...tokenRenderInput.cssProperties].reverse(),
    }))
    assert.throws(() => renderTokenInventory({ ...tokenRenderInput, tokenPaths: [{ value: "#fff" }] }), /names only/)

    const packageRoot = path.join(root, "repo")
    await writeFixtureManifest(path.join(packageRoot, "packages", "tokens"), {
      name: "@exre/exui-tokens",
      exports: { ".": { import: "./dist/index.js" }, "./style.css": "./dist/style.css", "./font.css": "./dist/font.css" },
    })
    await writeFixtureManifest(path.join(packageRoot, "packages", "components"), {
      name: "@exre/exui",
      exports: { ".": { types: "./types/index.d.ts" } },
    })
    await writeFixtureManifest(path.join(packageRoot, "packages", "showcase"), {
      name: "@exre/exui-showcase",
      private: true,
      exports: { ".": { types: "./types/index.d.ts" } },
    })
    const selection = { packages: [
      { role: "tokens", workspace: "packages/tokens", name: "@exre/exui-tokens" },
      { role: "components", workspace: "packages/components", name: "@exre/exui" },
    ] }
    await validatePackageSelection(packageRoot, selection)
    await expectRejection(() => validatePackageSelection(packageRoot, { packages: [selection.packages[0], { ...selection.packages[0] }] }), "roles must be unique")
    await expectRejection(() => validatePackageSelection(packageRoot, { packages: [selection.packages[0], { ...selection.packages[1], name: "wrong" }] }), "package name")
    await expectRejection(() => validatePackageSelection(packageRoot, { packages: [selection.packages[0], { ...selection.packages[1], workspace: "packages/showcase" }] }), "unapproved workspace")
    await expectRejection(() => validatePackageSelection(packageRoot, { packages: [selection.packages[0], { ...selection.packages[1], workspace: "../outside" }] }), "unapproved workspace")
    const tokensManifestPath = path.join(packageRoot, "packages", "tokens", "package.json")
    const tokensManifest = await readJson(tokensManifestPath)
    await writeFile(tokensManifestPath, `${JSON.stringify({ ...tokensManifest, private: true }, null, 2)}\n`, "utf8")
    await expectRejection(() => validatePackageSelection(packageRoot, selection), "private packages")
    await writeFile(tokensManifestPath, `${JSON.stringify(tokensManifest, null, 2)}\n`, "utf8")
    const escapingManifest = {
      ...tokensManifest,
      exports: { ...tokensManifest.exports, "./font.css": "../../outside.css" },
    }
    await writeFile(tokensManifestPath, `${JSON.stringify(escapingManifest, null, 2)}\n`, "utf8")
    await expectRejection(() => validatePackageSelection(packageRoot, selection), "resolves outside")
    await writeFile(tokensManifestPath, `${JSON.stringify(tokensManifest, null, 2)}\n`, "utf8")

    const humanRoot = path.join(root, "human")
    await createHumanDocumentFixture(humanRoot)
    await validateHumanDocuments(humanRoot)
    await writeFile(path.join(humanRoot, "SKILL.md"), `${await readFile(path.join(humanRoot, "SKILL.md"), "utf8")}\n[Missing](references/missing.md)\n`, "utf8")
    await expectRejection(() => validateHumanDocuments(humanRoot), "link does not exist")
    await createHumanDocumentFixture(humanRoot)
    await writeFile(path.join(humanRoot, "references", "token-usage.md"), `${await readFile(path.join(humanRoot, "references", "token-usage.md"), "utf8")}\n[Missing](missing.md)\n`, "utf8")
    await expectRejection(() => validateHumanDocuments(humanRoot), "link does not exist")
    await createHumanDocumentFixture(humanRoot)
    await writeFile(path.join(humanRoot, "references", "components", "Button.md"), "```tsx\n<Button><RefreshCwIcon /></Button>\n```\n", "utf8")
    await expectRejection(() => validateHumanDocuments(humanRoot), "missing its lucide-react import")
    await createHumanDocumentFixture(humanRoot)
    await writeFile(path.join(humanRoot, "references", "components", "Button.md"), `import { Button } from "@exre/exui/src/button"\n`, "utf8")
    await expectRejection(() => validateHumanDocuments(humanRoot), "private package import")

    const transactionRoot = path.join(root, "transaction")
    const originalOutputs = {
      "component-exports.md": renderComponentInventory([
        { category: "Components", family: "Button", kind: "value", name: "Button", reference: null },
      ]),
      "token-paths.md": renderTokenInventory({
        tokenPaths: ["exuiTokens.original"],
        recipePaths: ["componentRecipes.original"],
        cssProperties: ["--original"],
      }),
    }
    const replacementOutputs = {
      "component-exports.md": renderComponentInventory([
        { category: "Components", family: "Button", kind: "value", name: "ActionButton", reference: null },
      ]),
      "token-paths.md": renderTokenInventory({
        tokenPaths: ["exuiTokens.replacement"],
        recipePaths: ["componentRecipes.replacement"],
        cssProperties: ["--replacement"],
      }),
    }
    await mkdir(path.join(transactionRoot, "generated"), { recursive: true })
    for (const name of generatedFileNames) {
      await writeFile(path.join(transactionRoot, "generated", name), originalOutputs[name], "utf8")
    }
    const injectedOperations = {
      rename: async (source, destination) => {
        if (path.basename(source).startsWith(".generated-tmp-") && path.basename(destination) === "generated") {
          fail("injected directory switch failure")
        }
        await rename(source, destination)
      },
      rm,
    }
    await expectRejection(() => replaceGeneratedDirectory(replacementOutputs, transactionRoot, injectedOperations), "injected directory switch failure")
    for (const name of generatedFileNames) {
      assert.equal(await readFile(path.join(transactionRoot, "generated", name), "utf8"), originalOutputs[name])
    }
    const firstRenameFailureOperations = {
      rename: async (source, destination) => {
        if (path.basename(source) === "generated" && path.basename(destination) === ".generated-backup") {
          fail("injected backup switch failure")
        }
        await rename(source, destination)
      },
      rm,
    }
    await expectRejection(() => replaceGeneratedDirectory(replacementOutputs, transactionRoot, firstRenameFailureOperations), "injected backup switch failure")
    for (const name of generatedFileNames) {
      assert.equal(await readFile(path.join(transactionRoot, "generated", name), "utf8"), originalOutputs[name])
    }
    await rename(path.join(transactionRoot, "generated"), path.join(transactionRoot, ".generated-backup"))
    await recoverInterruptedWrite(transactionRoot)
    for (const name of generatedFileNames) {
      assert.equal(await readFile(path.join(transactionRoot, "generated", name), "utf8"), originalOutputs[name])
    }
  } finally {
    await rm(root, { recursive: true, force: true })
  }
  process.stdout.write("exui-usage updater self-test passed\n")
}

function parseMode(argumentsList) {
  const supported = new Set(["--write", "--check", "--self-test"])
  requireCondition(argumentsList.length === 1 && supported.has(argumentsList[0]), "usage: node skills/exui-usage/scripts/update.mjs (--write | --check | --self-test)")
  return argumentsList[0]
}

async function generateOutputs(packages) {
  const tokens = await loadTokenInventory(packages.tokens)
  const components = await loadComponentInventory(packages.components)
  const outputs = {
    "component-exports.md": renderComponentInventory(components),
    "token-paths.md": renderTokenInventory(tokens),
  }
  validateGeneratedOutputs(outputs, { tokens, components })
  return outputs
}

async function main() {
  const mode = parseMode(process.argv.slice(2))
  if (mode === "--self-test") {
    await runSelfTest()
    return
  }

  const packages = await loadPackageSelection()
  await validateHumanDocuments(skillRoot)
  buildPublicEntries()
  const outputs = await generateOutputs(packages)

  if (mode === "--check") {
    await checkGeneratedDirectory(outputs)
    process.stdout.write("exui-usage generated references are current\n")
    return
  }

  await replaceGeneratedDirectory(outputs)
  process.stdout.write("exui-usage generated references updated\n")
}

main().catch((error) => {
  process.stderr.write(`exui-usage update failed: ${error.message}\n`)
  process.exitCode = 1
})
