import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center border bg-clip-padding whitespace-nowrap transition-all outline-none select-none active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default:
          "[background:var(--exui-component-button-primary-default-background)] [color:var(--exui-component-button-primary-default-foreground)] [border-color:var(--exui-component-button-primary-default-border)] [box-shadow:var(--exui-component-button-primary-default-shadow)] opacity-[var(--exui-component-button-primary-default-opacity)] hover:[background:var(--exui-component-button-primary-hover-background)] hover:[color:var(--exui-component-button-primary-hover-foreground)] hover:[border-color:var(--exui-component-button-primary-hover-border)] hover:[box-shadow:var(--exui-component-button-primary-hover-shadow)] hover:opacity-[var(--exui-component-button-primary-hover-opacity)] active:[background:var(--exui-component-button-primary-active-background)] active:[color:var(--exui-component-button-primary-active-foreground)] active:[border-color:var(--exui-component-button-primary-active-border)] active:[box-shadow:var(--exui-component-button-primary-active-shadow)] active:opacity-[var(--exui-component-button-primary-active-opacity)] focus-visible:[background:var(--exui-component-button-primary-focus-background)] focus-visible:[color:var(--exui-component-button-primary-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-primary-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-primary-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-primary-focus-opacity)] disabled:[background:var(--exui-component-button-primary-disabled-background)] disabled:[color:var(--exui-component-button-primary-disabled-foreground)] disabled:[border-color:var(--exui-component-button-primary-disabled-border)] disabled:[box-shadow:var(--exui-component-button-primary-disabled-shadow)] disabled:opacity-[var(--exui-component-button-primary-disabled-opacity)]",
        danger:
          "[background:var(--exui-component-button-danger-default-background)] [color:var(--exui-component-button-danger-default-foreground)] [border-color:var(--exui-component-button-danger-default-border)] [box-shadow:var(--exui-component-button-danger-default-shadow)] opacity-[var(--exui-component-button-danger-default-opacity)] hover:[background:var(--exui-component-button-danger-hover-background)] hover:[color:var(--exui-component-button-danger-hover-foreground)] hover:[border-color:var(--exui-component-button-danger-hover-border)] hover:[box-shadow:var(--exui-component-button-danger-hover-shadow)] hover:opacity-[var(--exui-component-button-danger-hover-opacity)] active:[background:var(--exui-component-button-danger-active-background)] active:[color:var(--exui-component-button-danger-active-foreground)] active:[border-color:var(--exui-component-button-danger-active-border)] active:[box-shadow:var(--exui-component-button-danger-active-shadow)] active:opacity-[var(--exui-component-button-danger-active-opacity)] focus-visible:[background:var(--exui-component-button-danger-focus-background)] focus-visible:[color:var(--exui-component-button-danger-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-danger-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-danger-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-danger-focus-opacity)] disabled:[background:var(--exui-component-button-danger-disabled-background)] disabled:[color:var(--exui-component-button-danger-disabled-foreground)] disabled:[border-color:var(--exui-component-button-danger-disabled-border)] disabled:[box-shadow:var(--exui-component-button-danger-disabled-shadow)] disabled:opacity-[var(--exui-component-button-danger-disabled-opacity)]",
        outline:
          "[background:var(--exui-component-button-outline-default-background)] [color:var(--exui-component-button-outline-default-foreground)] [border-color:var(--exui-component-button-outline-default-border)] [box-shadow:var(--exui-component-button-outline-default-shadow)] opacity-[var(--exui-component-button-outline-default-opacity)] hover:[background:var(--exui-component-button-outline-hover-background)] hover:[color:var(--exui-component-button-outline-hover-foreground)] hover:[border-color:var(--exui-component-button-outline-hover-border)] hover:[box-shadow:var(--exui-component-button-outline-hover-shadow)] hover:opacity-[var(--exui-component-button-outline-hover-opacity)] active:[background:var(--exui-component-button-outline-active-background)] active:[color:var(--exui-component-button-outline-active-foreground)] active:[border-color:var(--exui-component-button-outline-active-border)] active:[box-shadow:var(--exui-component-button-outline-active-shadow)] active:opacity-[var(--exui-component-button-outline-active-opacity)] focus-visible:[background:var(--exui-component-button-outline-focus-background)] focus-visible:[color:var(--exui-component-button-outline-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-outline-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-outline-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-outline-focus-opacity)] disabled:[background:var(--exui-component-button-outline-disabled-background)] disabled:[color:var(--exui-component-button-outline-disabled-foreground)] disabled:[border-color:var(--exui-component-button-outline-disabled-border)] disabled:[box-shadow:var(--exui-component-button-outline-disabled-shadow)] disabled:opacity-[var(--exui-component-button-outline-disabled-opacity)]",
        secondary:
          "[background:var(--exui-component-button-secondary-default-background)] [color:var(--exui-component-button-secondary-default-foreground)] [border-color:var(--exui-component-button-secondary-default-border)] [box-shadow:var(--exui-component-button-secondary-default-shadow)] opacity-[var(--exui-component-button-secondary-default-opacity)] hover:[background:var(--exui-component-button-secondary-hover-background)] hover:[color:var(--exui-component-button-secondary-hover-foreground)] hover:[border-color:var(--exui-component-button-secondary-hover-border)] hover:[box-shadow:var(--exui-component-button-secondary-hover-shadow)] hover:opacity-[var(--exui-component-button-secondary-hover-opacity)] active:[background:var(--exui-component-button-secondary-active-background)] active:[color:var(--exui-component-button-secondary-active-foreground)] active:[border-color:var(--exui-component-button-secondary-active-border)] active:[box-shadow:var(--exui-component-button-secondary-active-shadow)] active:opacity-[var(--exui-component-button-secondary-active-opacity)] focus-visible:[background:var(--exui-component-button-secondary-focus-background)] focus-visible:[color:var(--exui-component-button-secondary-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-secondary-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-secondary-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-secondary-focus-opacity)] disabled:[background:var(--exui-component-button-secondary-disabled-background)] disabled:[color:var(--exui-component-button-secondary-disabled-foreground)] disabled:[border-color:var(--exui-component-button-secondary-disabled-border)] disabled:[box-shadow:var(--exui-component-button-secondary-disabled-shadow)] disabled:opacity-[var(--exui-component-button-secondary-disabled-opacity)]",
        ghost:
          "[background:var(--exui-component-button-ghost-default-background)] [color:var(--exui-component-button-ghost-default-foreground)] [border-color:var(--exui-component-button-ghost-default-border)] [box-shadow:var(--exui-component-button-ghost-default-shadow)] opacity-[var(--exui-component-button-ghost-default-opacity)] hover:[background:var(--exui-component-button-ghost-hover-background)] hover:[color:var(--exui-component-button-ghost-hover-foreground)] hover:[border-color:var(--exui-component-button-ghost-hover-border)] hover:[box-shadow:var(--exui-component-button-ghost-hover-shadow)] hover:opacity-[var(--exui-component-button-ghost-hover-opacity)] active:[background:var(--exui-component-button-ghost-active-background)] active:[color:var(--exui-component-button-ghost-active-foreground)] active:[border-color:var(--exui-component-button-ghost-active-border)] active:[box-shadow:var(--exui-component-button-ghost-active-shadow)] active:opacity-[var(--exui-component-button-ghost-active-opacity)] focus-visible:[background:var(--exui-component-button-ghost-focus-background)] focus-visible:[color:var(--exui-component-button-ghost-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-ghost-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-ghost-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-ghost-focus-opacity)] disabled:[background:var(--exui-component-button-ghost-disabled-background)] disabled:[color:var(--exui-component-button-ghost-disabled-foreground)] disabled:[border-color:var(--exui-component-button-ghost-disabled-border)] disabled:[box-shadow:var(--exui-component-button-ghost-disabled-shadow)] disabled:opacity-[var(--exui-component-button-ghost-disabled-opacity)]",
        destructive:
          "[background:var(--exui-component-button-danger-default-background)] [color:var(--exui-component-button-danger-default-foreground)] [border-color:var(--exui-component-button-danger-default-border)] [box-shadow:var(--exui-component-button-danger-default-shadow)] opacity-[var(--exui-component-button-danger-default-opacity)] hover:[background:var(--exui-component-button-danger-hover-background)] hover:[color:var(--exui-component-button-danger-hover-foreground)] hover:[border-color:var(--exui-component-button-danger-hover-border)] hover:[box-shadow:var(--exui-component-button-danger-hover-shadow)] hover:opacity-[var(--exui-component-button-danger-hover-opacity)] active:[background:var(--exui-component-button-danger-active-background)] active:[color:var(--exui-component-button-danger-active-foreground)] active:[border-color:var(--exui-component-button-danger-active-border)] active:[box-shadow:var(--exui-component-button-danger-active-shadow)] active:opacity-[var(--exui-component-button-danger-active-opacity)] focus-visible:[background:var(--exui-component-button-danger-focus-background)] focus-visible:[color:var(--exui-component-button-danger-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-danger-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-danger-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-danger-focus-opacity)] disabled:[background:var(--exui-component-button-danger-disabled-background)] disabled:[color:var(--exui-component-button-danger-disabled-foreground)] disabled:[border-color:var(--exui-component-button-danger-disabled-border)] disabled:[box-shadow:var(--exui-component-button-danger-disabled-shadow)] disabled:opacity-[var(--exui-component-button-danger-disabled-opacity)]",
        link:
          "[background:var(--exui-component-button-link-default-background)] [color:var(--exui-component-button-link-default-foreground)] [border-color:var(--exui-component-button-link-default-border)] [box-shadow:var(--exui-component-button-link-default-shadow)] opacity-[var(--exui-component-button-link-default-opacity)] underline-offset-4 hover:[background:var(--exui-component-button-link-hover-background)] hover:[color:var(--exui-component-button-link-hover-foreground)] hover:[border-color:var(--exui-component-button-link-hover-border)] hover:[box-shadow:var(--exui-component-button-link-hover-shadow)] hover:opacity-[var(--exui-component-button-link-hover-opacity)] hover:underline active:[background:var(--exui-component-button-link-active-background)] active:[color:var(--exui-component-button-link-active-foreground)] active:[border-color:var(--exui-component-button-link-active-border)] active:[box-shadow:var(--exui-component-button-link-active-shadow)] active:opacity-[var(--exui-component-button-link-active-opacity)] focus-visible:[background:var(--exui-component-button-link-focus-background)] focus-visible:[color:var(--exui-component-button-link-focus-foreground)] focus-visible:[border-color:var(--exui-component-button-link-focus-border)] focus-visible:[box-shadow:var(--exui-component-button-link-focus-shadow)] focus-visible:opacity-[var(--exui-component-button-link-focus-opacity)] disabled:[background:var(--exui-component-button-link-disabled-background)] disabled:[color:var(--exui-component-button-link-disabled-foreground)] disabled:[border-color:var(--exui-component-button-link-disabled-border)] disabled:[box-shadow:var(--exui-component-button-link-disabled-shadow)] disabled:opacity-[var(--exui-component-button-link-disabled-opacity)]",
      },
      size: {
        default:
          "h-[var(--exui-component-button-default-height)] gap-[var(--exui-component-button-default-gap)] rounded-[var(--exui-component-button-default-radius)] px-[var(--exui-component-button-default-padding-inline)] [font-family:var(--exui-component-button-default-font-family)] text-[length:var(--exui-component-button-default-font-size)] leading-[var(--exui-component-button-default-line-height)] font-[number:var(--exui-component-button-default-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-default-icon-size)]",
        xs: "h-[var(--exui-component-button-small-height)] gap-[var(--exui-component-button-small-gap)] rounded-[var(--exui-component-button-small-radius)] px-[var(--exui-component-button-small-padding-inline)] [font-family:var(--exui-component-button-small-font-family)] text-[length:var(--exui-component-button-small-font-size)] leading-[var(--exui-component-button-small-line-height)] font-[number:var(--exui-component-button-small-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-small-icon-size)]",
        sm: "h-[var(--exui-component-button-small-height)] gap-[var(--exui-component-button-small-gap)] rounded-[var(--exui-component-button-small-radius)] px-[var(--exui-component-button-small-padding-inline)] [font-family:var(--exui-component-button-small-font-family)] text-[length:var(--exui-component-button-small-font-size)] leading-[var(--exui-component-button-small-line-height)] font-[number:var(--exui-component-button-small-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-small-icon-size)]",
        lg: "h-[var(--exui-component-button-large-height)] gap-[var(--exui-component-button-large-gap)] rounded-[var(--exui-component-button-large-radius)] px-[var(--exui-component-button-large-padding-inline)] [font-family:var(--exui-component-button-large-font-family)] text-[length:var(--exui-component-button-large-font-size)] leading-[var(--exui-component-button-large-line-height)] font-[number:var(--exui-component-button-large-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-large-icon-size)]",
        icon: "size-[var(--exui-component-button-icon-height)] gap-[var(--exui-component-button-icon-gap)] rounded-[var(--exui-component-button-icon-radius)] px-[var(--exui-component-button-icon-padding-inline)] [font-family:var(--exui-component-button-icon-font-family)] text-[length:var(--exui-component-button-icon-font-size)] leading-[var(--exui-component-button-icon-line-height)] font-[number:var(--exui-component-button-icon-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-icon-icon-size)]",
        "icon-xs": "size-[var(--exui-component-button-small-height)] gap-[var(--exui-component-button-icon-gap)] rounded-[var(--exui-component-button-icon-radius)] px-[var(--exui-component-button-icon-padding-inline)] [font-family:var(--exui-component-button-small-font-family)] text-[length:var(--exui-component-button-small-font-size)] leading-[var(--exui-component-button-small-line-height)] font-[number:var(--exui-component-button-small-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-icon-icon-size)]",
        "icon-sm": "size-[var(--exui-component-button-small-height)] gap-[var(--exui-component-button-icon-gap)] rounded-[var(--exui-component-button-icon-radius)] px-[var(--exui-component-button-icon-padding-inline)] [font-family:var(--exui-component-button-small-font-family)] text-[length:var(--exui-component-button-small-font-size)] leading-[var(--exui-component-button-small-line-height)] font-[number:var(--exui-component-button-small-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-icon-icon-size)]",
        "icon-lg": "size-[var(--exui-component-button-large-height)] gap-[var(--exui-component-button-icon-gap)] rounded-[var(--exui-component-button-icon-radius)] px-[var(--exui-component-button-icon-padding-inline)] [font-family:var(--exui-component-button-large-font-family)] text-[length:var(--exui-component-button-large-font-size)] leading-[var(--exui-component-button-large-line-height)] font-[number:var(--exui-component-button-large-font-weight)] [&_svg:not([class*='size-'])]:size-[var(--exui-component-button-icon-icon-size)]",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

function ActionButton({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="action-button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    />
  )
}

export { Button, ActionButton, buttonVariants }
